# This checks for successful compilation of test.ts.
# This file and code is generated automatically by 'mkc init'.

name: MakeCode Build
on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - run: npx makecode
